### ISSUE TITLE
Class Alias support

### ISSUE THREAD

**Issue by ghost** [perceptron8/amf#1]
Hello!

I'm using your AMF library in a port of Actionscript 3's ByteArray, written in JavaScript. In the AMF3 class, I see in the object serialization "@name". Is this used for class aliases? It would be nice if you were to update this library if needed.

**Comment by perceptron8** [comment]
Hi!

If I understand your question correctly, then yes, `@name` property is used to store class / traits alias. For details, please see [amf-file-format-spec.pdf](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/amf-file-format-spec.pdf) (3.12 Object type).

You may also like to review following methods:
https://github.com/perceptron8/amf/blob/00a922a74434dcdc3c17c791a41d9cc692374e55/lib/AMF3/Reader.js#L107-L168 https://github.com/perceptron8/amf/blob/00a922a74434dcdc3c17c791a41d9cc692374e55/lib/AMF3/Writer.js#L108-L163

In principle, this library was designed with dynamically intercepting and modifying AMF Messages (with partially unknown, constantly evolving content) in mind, thus there's no any kind of static types / schemas involved. If that's enough for you, great. If you need something more, feel free to fork and extend or just build something new on the foundation of this library. That said, I promise that 'll try to maintain it and fix any bugs you (or anyone else) find.

Thanks for asking :)

**Comment by ghost** [comment]
Thanks for replying that quickly. I just have one more question, what if I want to register more class aliases on 1 object? I'd suggest you push an update that uses registerClassAlias in an array or something.

**Comment by perceptron8** [comment]
My first impression is that this is out of scope of this library. Could you give me some real use case - preferably including source code? I'd like to understand, why registering multiple aliases would be ever needed.

BTW I can't find anything about class aliases that is ActionScript or JavaScript related. "alias" is used twice within AMF3 spec, but it looks to me like there will be always one alias for one class.

**Comment by ghost** [comment]
Well it doesn't matter anyway. About to send a PR for supporting mixed arrays (I'm using your library in something, from real Adobe AMF3 to Javascript)
