### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by ghost** [perceptron8/amf#3]
Hey again!

I'm making an independent "one-file" AMF0 & AMF3 library for Node.js and I stumbled upon something interesting.

I just have a small question related to object serialization for AMF3 in this library. I'm a bit worried about writeObject and readObject not being correct. Is the implementation of the 2 functions identical to Actionscript 3's?

I also found a potential bug in writeObject:

```javascript
const name = _.result(object, "@name", "");

this.traits.set(name, this.traits.size);
```

When `@name` is not in the object, the const `name` will be an empty string. In my case, I don't have to construct another AMF dependency as I can just read straight away, so the references don't get reset, following that `this.traits` is a string and not an object, causing the following code for `readObject` to throw an exception.

The code for that is:

```javascript
for (let property of object["@properties"]) {
  assert(property[0] != "@");
  const value = this.read();
  object[property] = value;
}
```

The error should be that it can't iterate, because it's a string. I'm just going to note this all just so you know, but I fixed it by adding this code into writeObject:

```javascript
if (name !== "") {
   this.traits.set(name, this.traits.size)
}
```

**Comment by perceptron8** [comment]
> Is the implementation of the 2 functions identical to Actionscript 3's?

Obviously not. This is javascript, not ActionScript. At the same time, I hope this implementation is as close to [amf-file-format-spec.pdf](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/amf-file-format-spec.pdf) as possible.

> When @name is not in the object, the const name will be an empty string. In my case, I don't have to construct another AMF dependency as I can just read straight away, so the references don't get reset, following that this.traits is a string and not an object, causing the following code for readObject to throw an exception.

What do you mean by another AMF dependency? What makes you think that `this.traits` is a string and not an object? Can you provide a [MCVE](https://stackoverflow.com/help/mcve). Please, fork and add some additional _spec/*_ if you like.

If I understand you correctly, you are talking about situation, where two anonymous (unnamed) classes are serialized and as a consequence both refer to the same metadata (single trait) within `Writer.traits` map? Is that it?

**Comment by ghost** [comment]
Well I just removed my fix and tried it again to create the exception but suddenly I'm not getting it anymore. It seems pretty weird and I don't even understand what happened anymore. I guess this should be ignored. I do think that the object serialization / deserialization is pretty messy. We should take an example to [James Ward's object deserialization](https://github.com/jamesward/JSAMF/blob/master/web/web/amf.js#L992-L1038) and create a serializer.

**Comment by ghost** [comment]
You can find my library [here](https://github.com/Zaseth/amf4js)

**Comment by ghost** [comment]
What's the purpose of this:

https://github.com/perceptron8/amf/blob/master/lib/AMF3/Writer.js#L133

**Comment by perceptron8** [comment]
> What's the purpose of this:
> 
> https://github.com/perceptron8/amf/blob/master/lib/AMF3/Writer.js#L133

This is some form of validation of `object["@properties"]` elements (it comes from users, so it can be anything). Assert is here also because of self-documenting purpose.

I' trying to preserve clear distinction between regular properties and traits/annotations (just by conventions their names start with @).

**Comment by ghost** [comment]
Is there anything you happen to have in mind to implement in your AMF library?

**Comment by perceptron8** [comment]
> Is there anything you happen to have in mind to implement in your AMF library?

Not really... at least not right now.

**Comment by ghost** [comment]
I noticed that you're using strict arrays in AMF0. AMF0 defaults to ECMA arrays. Why did you make this decision?

**Comment by perceptron8** [comment]
> I noticed that you're using strict arrays in AMF0. AMF0 defaults to ECMA arrays. Why did you make this decision?

Otherwise I wouldn't be able to serialize dense arrays (sparse arrays can be still serialized as Objects). Some decision had to be made. I decided to support just one type of arrays. Maybe I should introduce wrappers as discussed in #2 back then, but that would be less JSON-oriented solution. As always, I was aiming for maximum simplicity.

Why are you asking? Is my lib incompatible with some existing AMF0 implementation? Or you are just curious?

**Comment by ghost** [comment]
I'm just asking out of curiosity
